#!/usr/bin/env python3
"""
CoChem Setup Phase 5: Academic Output, Offloading, & Finalization
Generates Codespaces offload YAML, strict locks, final IPC config,
and organizes the main directory to prevent workspace clutter.

*UPDATED*: Now integrates the Golden Gatekeeper (RegistryManager) 
for atomic, schema-validated configuration persistence.
"""

import os
import sys
import json
import logging
from pathlib import Path

# Add project root to sys.path to allow imports from Libraries
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

from Libraries.cochem_registry_manager import RegistryManager
from Libraries.cochem_registry_schema import CoChemConfig, HardwareConfig, EnginePaths, HPCConfig

class Colors:
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'

def print_status(msg: str, status: str = "info") -> None:
    if status == "success":
        print(f" {Colors.OKGREEN}✅ {msg}{Colors.ENDC}")
    elif status == "warning":
        print(f" {Colors.WARNING}⚠️ {msg}{Colors.ENDC}")
    elif status == "fail":
        print(f" {Colors.FAIL}❌ {msg}{Colors.ENDC}")
    else:
        print(f" ➡️ {msg}")

def read_phase_data() -> dict:
    """
    Simulates reading the aggregated setup data generated by Phases 1-4.
    In a live execution, this reads the temporary state `.cochem_build_state.json`.
    """
    state_file = PROJECT_ROOT / ".cochem_build_state.json"
    if not state_file.exists():
        print_status("No intermediate build state found. Using default fallbacks.", "warning")
        return {}
    
    with open(state_file, 'r') as f:
        return json.load(f)

def compile_final_registry():
    """
    Ingests phase data, maps to Pydantic schema, and atomically saves.
    """
    print_status("Initializing Golden Gatekeeper (Registry Manager)...")
    collected_data = read_phase_data()
    
    registry_path = PROJECT_ROOT / "cochem_system_config.json"
    manager = RegistryManager(str(registry_path))

    # Map raw data to nested Pydantic schemas
    try:
        hardware = HardwareConfig(
            cpu_cores=collected_data.get('cpu_cores', os.cpu_count() or 4),
            ram_mb=collected_data.get('ram_mb', 8192),
            avx512_support=collected_data.get('avx512_support', False),
            host_id=collected_data.get('host_id', 'UNKNOWN-HOST')
        )

        engines = EnginePaths(
            orca_path=collected_data.get('orca_path', ''),
            openmpi_path=collected_data.get('openmpi_path', ''),
            mace_model_path=collected_data.get('mace_model_path', None)
        )

        hpc = HPCConfig(
            cluster_hostname=collected_data.get('cluster_hostname', ''),
            partition=collected_data.get('partition', 'normal'),
            ssh_key_path=collected_data.get('ssh_key_path', ''),
            username=collected_data.get('username', '')
        )

        # Construct the Golden Gatekeeper payload
        valid_config = CoChemConfig(
            registry_version="2.0",
            hardware=hardware,
            engines=engines,
            hpc=hpc
        )
        
        # Inject the validated Pydantic model into the Manager and execute Atomic Save
        manager.config = valid_config
        manager.save()
        print_status(f"Registry successfully locked and verified at {registry_path.name}", "success")
        
    except Exception as e:
        print_status(f"Fatal Schema Generation Error: {e}", "fail")
        sys.exit(1)

def cleanup_workspace():
    """Removes temporary build files."""
    state_file = PROJECT_ROOT / ".cochem_build_state.json"
    if state_file.exists():
        os.remove(state_file)
        print_status("Workspace cleanup complete.", "success")

def main() -> None:
    print(f"\n{Colors.BOLD}--- Phase 5: Ecosystem Integration & Finalization ---{Colors.ENDC}")
    compile_final_registry()
    cleanup_workspace()
    print_status("CoChem Initialization Sequence Complete.", "success")

if __name__ == "__main__":
    main()